apiVersion: v1
data:
  config.yaml: |+
    ---
    slackChannel: group-b-status
    slackAdminChannel: group-b-bots
    cachePath: /cache/bugzilla.db
    credentials:
      username: base64:
      password: base64:
      apiKey: base64:
      slackToken:
    components:
    - apiserver-auth
    - config-operator
    - Etcd
    - Etcd Operator
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-storage-version-migrator
    - Master
    - oauth-apiserver
    - oauth-proxy
    - oc
    - openshift-apiserver
    - service-ca
    release:
      currentTargetRelease: 4.5.0
      targetReleases:
      - 3.11.z
      - 4.2.z
      - 4.3.z
      - 4.4.z
      - 4.5.0
      - 4.6.0
    staleBugCloseComment: >
      This bug hasn't had any activity 7 days after it was marked as LifecycleStale, so we are closing this bug as WONTFIX.
      If you consider this bug still valuable, please reopen it or create new bug.
    staleBugComment: >
      This bug hasn't had any activity in the last 30 days. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.
      As such, we're marking this bug as "LifecycleStale" and decreasing the severity/priority.
      If you have further information on the current state of the bug, please update it, otherwise this bug can be closed in about 7 days. The information can be, for example, that the problem still occurs,
      that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.
    groups:
      admins:
      - mfojtik
      - sttts
      leads:
      - deads2k
      - hexfusion
      - maszulik
      - mfojtik
      - sttts
      api-auth:
      - sttts
      - deads2k
      - polynomial
      - Standa
      - akashem
      - Luis Sanchez
      - vareti
      - marun
kind: ConfigMap
metadata:
  name: operator-config
  namespace: bugzilla-operator
