apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fedora
  namespace: bugzilla-operator
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: fedora:32
    from:
      kind: DockerImage
      name: fedora:32
    name: "32"
    referencePolicy:
      type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: bugzilla-operator
  namespace: bugzilla-operator
spec:
  lookupPolicy:
    local: true
