apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bugzilla-operator
  name: cache
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
