kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: bugzilla-operator
  name: state-editor
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["state"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: bugzilla-operator
  name: state-editor
subjects:
- kind: ServiceAccount
  name: default
  namespace: bugzilla-operator
roleRef:
  kind: Role
  name: state-editor
  apiGroup: rbac.authorization.k8s.io
