apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bugzilla-operator
  name: bugzilla-operator
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"bugzilla-operator:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"operator\")].image"}]'
  labels:
    app: bugzilla-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bugzilla-operator
  template:
    metadata:
      name: bugzilla-operator
      labels:
        app: bugzilla-operator
    spec:
      containers:
      - command:
        - bugzilla-operator
        - run
        - -v=9
        - --config
        - /var/run/operator-config/config.yaml
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker-registry.default.svc:5000/bugzilla-operator/bugzilla-operator@sha256:e392b7b67f6664429b90f7886af5d6484a5157189032538ebba49d05a5317b85
        name: operator
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/run/operator-config
          name: config
        - mountPath: /cache
          name: volume-3yrc5
      volumes:
      - configMap:
          defaultMode: 420
          name: operator-config
          optional: true
        name: config
      - name: volume-3yrc5
        persistentVolumeClaim:
          claimName: cache
