---
credentials:
  username:
  password:
  apiKey:
lists:
  staleListName: openshift-group-b-stale
  sharerID: 290313
devWhiteboardFlag: LifecycleStale
staleBugComment: >
  This bug hasn't had any activity in the last 30 days. Maybe the problem got resolved, was a duplicate of something else, or became less pressing for some reason - or maybe it's still relevant but just hasn't been looked at yet.
  As such, we're marking this bug as "LifecycleStale" and decreasing the severity/priority.
  If you have further information on the current state of the bug, please update it, otherwise this bug can be closed in about 7 days. The information can be, for example, that the problem still occurs,
  that you still want the feature, that more information is needed, or that the bug is (for whatever reason) no longer relevant.
